name: Deploy
on:
  push:
    branches:
      - main
jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: slack-notification
        uses: premisedata/slack-build-notifications@v1.0
        if: always()
        env:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}

