name: Deploy
on:
  push:
    branches:
      - main
jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: slack-notification-for-failure
        uses: codigube/github-actions-notify-slack@v3.0.0
        if: failure() || cancelled()
        env:
          SLACK_COLOR: '#DF5A49'
          SLACK_MESSAGE: 'Job ${{ github.job }} failed'

      - name: slack-notification-for-success
        uses: codigube/github-actions-notify-slack@v3.0.0
        if: success()
        env:
          SLACK_MESSAGE: 'Job ${{ github.job }} succeeded'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

