name: Deploy
on:
  push:
    branches:
      - main
jobs:
  slack:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2



      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#cicd'
          message: |
            *<{{refUrl}}|PR _{{description}}({{ref}})_ requires code review>*
            {{#if payload.pull_request.requested_reviewers }}
            *Please, the following users check the code and accept/reject accordingly:*
            {{#each payload.pull_request.requested_reviewers}}
            :white_check_mark: <{{this.url}}|`{{this.login}}`>
            {{/each}}
            {{/if}}
        if: always()