name: Deploy
on:
  push:
    branches:
      - main
jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Slack Notify About Conflicts
        uses: brainly/action-slack-notificator
        with:
          webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          messageContent: 'Your custom message!'

